apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-authz
  labels:
    app: ns-authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-authz
  template:
    metadata:
      labels:
        app: ns-authz
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: ns-authz
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "/scripts/watcher.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: ns-authz-script
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
